### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by webdevbrian** [Maxorq/LastPlug#21]

**Comment by Maxorq** [comment]
obviously

**Comment by webdevbrian** [comment]
Hahaha you must be an amazing dev. I would can the repo if it's dead, buddy!

**Comment by Maxorq** [comment]
i'm bad at coding and i don't really mind it existing

**Comment by webdevbrian** [comment]
My reply was absolutely sarcastic.

Kill the repo so other people KNOW it's dead, rather than someone coming in and having to create an issue just because you abandoned it completely.

Christ sake, update the Readme file at the very least. Just a protip if you're actually othering other repos, or plan too, anytime in the future.

Thanks

**Comment by Maxorq** [comment]
thanks for reminding me i'm useless

**Comment by webdevbrian** [comment]
It's a critique, you should take it as such.

Good luck!
